### ISSUE TITLE
Key Board Type Button is not working?

### ISSUE THREAD

**Issue by MTaimurAzhar** [mopsicus/unity-keyboard-hack#3]
Key board type "Next", "Search", "Done" are not working?

**Comment by MTaimurAzhar** [comment]
![1ac4fa95-48c9-4afc-be5f-8a69fd9f77a2](https://user-images.githubusercontent.com/26604981/54980934-87aba900-4fc0-11e9-9733-da88a139df84.jpg)

**Comment by mopsicus** [comment]
this repo is out of date, check the new https://github.com/mopsicus/UnityMobileInput
